BASE_URL = "https://smsdrop.edevtecapps.com"
USER_PATH = "/users/me"
LOGIN_PATH = "/auth/login"
CAMPAIGN_BASE_PATH = "/campaigns"
CAMPAIGN_RETRY_PATH = CAMPAIGN_BASE_PATH + "/retry"
SUBSCRIPTION_PATH = "/subscriptions/"
